### ISSUE TITLE
chmod: cannot access '/opt/ibm/cluster/ssh_key': No such file or directory

### ISSUE THREAD

**Issue by jaricsng** [pjgunadi/ibm-cloud-private-terraform-nutanix#1]
terraform plan failed with error

chmod: cannot access '/opt/ibm/cluster/ssh_key': No such file or directory
IOError: [Errno 2] No such file or directory: '/opt/ibm/cluster/config.yaml'

![image](https://user-images.githubusercontent.com/15228438/52170578-cf177500-2787-11e9-9411-9c858eeff246.png)

**Comment by pjgunadi** [comment]
related to issue #4. Fixed with correct docker repository name
