### ISSUE TITLE
error update with changing in cpu and ram

### ISSUE THREAD

**Issue by jaricsng** [pjgunadi/ibm-cloud-private-terraform-nutanix#10]
- deploy a node
- increase cpu and ram of node

encountered below error

![image](https://user-images.githubusercontent.com/15228438/52174472-1a08ab00-27cf-11e9-90bc-1cd9487825ae.png)

then change value back, run terraform plan, encountered below error message.

![image](https://user-images.githubusercontent.com/15228438/52174508-b7fc7580-27cf-11e9-98bf-b3fb31de4eec.png)

**Comment by pjgunadi** [comment]
error due to insufficient resource in the environment
