### ISSUE TITLE
docker not installed in node

### ISSUE THREAD

**Issue by jaricsng** [pjgunadi/ibm-cloud-private-terraform-nutanix#14]
it is observed when there is another process encountered during installation for apt-get message, docker is not installed and will break icp installation.

need to wait longer for lock to be released.

![image](https://user-images.githubusercontent.com/15228438/52296540-a1b20d80-29b9-11e9-9cd8-1aec82307ab2.png)

**Comment by pjgunadi** [comment]
download docker sometimes failed due to network. added option to download ICP bundled docker installer from local infra.
