### ISSUE TITLE
tf multi master with nfs

### ISSUE THREAD

**Issue by jaricsng** [pjgunadi/ibm-cloud-private-terraform-nutanix#15]
deploy 3 masters with nfs and noted the below message, is storage correctly mounted?

![image](https://user-images.githubusercontent.com/15228438/52296642-dcb44100-29b9-11e9-8fcd-f133e9b3eaa8.png)

**Comment by pjgunadi** [comment]
Fixed nfs server setup and nfs client mounting scripts
