### ISSUE TITLE
encountered: Maximum number of retries (20) for apt-get install attempted; quitting

### ISSUE THREAD

**Issue by jaricsng** [pjgunadi/ibm-cloud-private-terraform-nutanix#16]
when it happen, installation of docker is not installed.

nodes that encountered: Maximum number of retries (20) for apt-get install attempted; quitting, that node will failed install.

![image](https://user-images.githubusercontent.com/15228438/52297202-27828880-29bb-11e9-9c68-26dda19706ae.png)

**Comment by pjgunadi** [comment]
error due to download from internet. added option to download docker from local infrastructure.
also use parallelism=x during install
