### ISSUE TITLE
unable to resolve host

### ISSUE THREAD

**Issue by jaricsng** [pjgunadi/ibm-cloud-private-terraform-nutanix#2]
cannot resolve host

![image](https://user-images.githubusercontent.com/15228438/52170611-7bf1f200-2788-11e9-8372-542a2c7a4706.png)

**Comment by pjgunadi** [comment]
It is warning message due to hostname has changed and VM has not been restarted.

**Comment by pjgunadi** [comment]
assign hostname from cloud-init instead of script
