### ISSUE TITLE
terraform destroy error

### ISSUE THREAD

**Issue by jaricsng** [pjgunadi/ibm-cloud-private-terraform-nutanix#3]
encountered error on plan, performed destroy.
encountered the following error.

![image](https://user-images.githubusercontent.com/15228438/52170633-d5f2b780-2788-11e9-81d4-e735714b0726.png)
[log.txt](https://github.com/pjgunadi/ibm-cloud-private-terraform-nutanix/files/2825014/log.txt)

**Comment by pjgunadi** [comment]
Applied fix replaced default_ip_address variable
