### ISSUE TITLE
Unable to find image 'ibmcom/icp-inception:3.1.1-ee' locally

### ISSUE THREAD

**Issue by jaricsng** [pjgunadi/ibm-cloud-private-terraform-nutanix#4]
apply and failed with error below

Unable to find image 'ibmcom/icp-inception:3.1.1-ee' locally 

![image](https://user-images.githubusercontent.com/15228438/52171073-0c343500-2791-11e9-89ca-4dc3c6482ff7.png)

**Comment by pjgunadi** [comment]
Use icp_version="ibmcom/icp-inception-amd64:3.1.1-ee"  in variable
