### ISSUE TITLE
error on destroy : unable to read client cert

### ISSUE THREAD

**Issue by jaricsng** [pjgunadi/ibm-cloud-private-terraform-nutanix#5]
![image](https://user-images.githubusercontent.com/15228438/52173170-84aeec00-27b9-11e9-93e0-1b4eb67d9cd2.png)

**Comment by pjgunadi** [comment]
File path location has changed recently in ICP 3.1.1

**Comment by pjgunadi** [comment]
Fixed with 3.1.1 path
